version: '3'
services:
  redis-server:
    image: 'redis'
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
