version: '3'
services:
  redis-server:
    image: 'redis'
  server:
    image: 'nitishyadav169/voosh-server:latest'
    ports:
      - "8081:8081"
  web:
    image: 'nitishyadav169/voosh-client:latest'
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./client:/app
